version: '3'

services:
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=1
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWD}
      - MYSQL_DATABASE=${DB_NAME}
    networks:
      - prestashop
    volumes:
      - prestashop:/var/lib/mysql

  prestashop:
    image: prestashop/prestashop:1.7.6.7
    environment:
      - DB_SERVER=mysql
      - DB_PREFIX=ps1767_
      - PS_DEV_MODE=${PS_DEV_MODE}
      - PS_INSTALL_AUTO=1
      - DB_USER=${DB_USER}
      - DB_PASSWD=${DB_PASSWD}
      - DB_NAME=${DB_NAME}
      - PS_FOLDER_ADMIN=${PS_FOLDER_ADMIN}
      - PS_DOMAIN=${PS_DOMAIN}:8989
      - PS_LANGUAGE=${PS_LANGUAGE}
      - PS_COUNTRY=${PS_COUNTRY}
      - PS_FOLDER_INSTALL=installed
    networks:
      - prestashop
    depends_on:
      - mysql
    volumes:
      - ./${PS_MODULE_NAME}:/var/www/html/modules/${PS_MODULE_NAME}
    ports:
      - 8989:80


networks:
  prestashop:

volumes:
  prestashop:
